default_language_version:
  python: python3.12

ci:
  autofix_prs: true
  autoupdate_schedule: quarterly
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  # submodules: true

exclude: ^(.?venv)

repos:

- repo: https://github.com/pre-commit/pre-commit
  rev: v3.7.1
  hooks:
  - id: validate_manifest

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=204800, --enforce-all]
  - id: end-of-file-fixer
    exclude: ^.*\.egg-info/
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: check-json
  - id: check-xml
  - id: check-yaml
    args: [--unsafe]
  - id: pretty-format-json
    args: [--autofix, --no-ensure-ascii, --no-sort-keys]
  - id: check-ast
  - id: debug-statements
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: fix-byte-order-marker
  - id: mixed-line-ending
    args: ['--fix=lf']

- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.4.9'
  hooks:
    # Run the linter.
    - id: ruff
      args: [--fix]
    # Run the formatter.
    - id: ruff-format

# - repo: https://github.com/asottile/pyupgrade
#   rev: v3.15.0
#   hooks:
#   - id: pyupgrade
#     args: [--py312-plus]
#     exclude: ^(install|get)-poetry.py$

# - repo: https://github.com/psf/black
#   rev: 23.11.0
#   hooks:
#   - id: black
#     name: black
#     entry: black
#     types: [python]
#     require_serial: true
